[project]
name = "Joker"
version = "0.1.0"
description = "JOKER - Jogo de Conhecimento"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
    "textual>=6.8.0",
    "textual-dev>=1.8.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]